### ISSUE TITLE
CSS selector discussion

### ISSUE THREAD

**Issue by afshin** [jupyterlab/lumino#9]
Should all of the legacy `p-*` CSS selectors be renamed to `lm-*`?
- In the interest of clarity (and purity), my intuition is "yes"
- In the interest of lower churn and a smaller amount of of pain imposed on current consumers of these APIs, "no" seems better.

**Comment by jasongrout** [comment]
I think this should be a change for Lumino 2.0.

**Comment by afshin** [comment]
So you think it should be a "yes" ... eventually? Do you think there's room for just leaving them as is or do you consider it too much of an inconsistency in nomenclature to keep the `p-*` classes?

**Comment by jasongrout** [comment]
I think the community around Lumino is just starting, and it's more valuable in the long term to have `lm-` prefixes.

So my intuition is "yes, at the earliest opportunity, which is 2.0".

**Comment by jasongrout** [comment]
In fact, I think if that is our decision, we should add `lm-` classes right now, and deprecate `p-` classes even before 2.0.

**Comment by afshin** [comment]
> In fact, I think if that is our decision, we should add lm- classes right now, and deprecate p- classes even before 2.0.

This is a good idea.

**Comment by vidartf** [comment]
> deprecate p- classes even before 2.0.

I'm not sure what you mean here. The way I read semver, you cannot remove anything (whether deprecated or not) in a minor release.

**Comment by afshin** [comment]
We won't remove it. We'll add a note that the selector is deprecated, but it will continue to work until 2.0 and the `lm-*` will work as well.

**Comment by afshin** [comment]
Hm.

I am not sure we can support the legacy deprecation because when we are checking for `p-mod-foo` in the TS code, do we now need to check for either `p-mod-foo` and also `lm-mod-foo`?

**Comment by afshin** [comment]
Okay, so the crux of the question is encapsulated in this example CSS:

```css
/* <DEPRECATED> */
.p-TabBar-tab.p-mod-hidden,
/* </DEPRECATED> */
.lm-TabBar-tab.lm-mod-hidden {
  display: none !important;
}
```

The `.p-mod-hidden` inside the deprecated class should never naturally arise once we switch to using `lm-mod-hidden`, however a consumer may have written custom CSS that targets something with a `p-mod-hidden` class on it. This is a problem that cannot be solved in pure CSS. So the question that arises is: **should we add `p-mod-hidden` in addition to `lm-mod-hidden` in the TS logic?** This doesn't feel correct to me.

**Comment by jasongrout** [comment]
In other words, are you asking if it should be as follows while it is deprecated?

```css
/* <DEPRECATED> */
.p-TabBar-tab.p-mod-hidden,
.lm-TabBar-tab.p-mod-hidden,
.p-TabBar-tab.lm-mod-hidden,
/* </DEPRECATED> */
.lm-TabBar-tab.lm-mod-hidden {
  display: none !important;
}
```
